-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.environmental
(
    company_id character varying(10) COLLATE pg_catalog."default",
    year integer,
    carbon_emissions numeric,
    energy_use numeric,
    waste_recycled numeric
);

CREATE TABLE IF NOT EXISTS public.esg_scores
(
    company_id character varying(10) COLLATE pg_catalog."default",
    year integer,
    environmetal_score numeric,
    social_score numeric,
    governance_score numeric,
    esg_score numeric
);

CREATE TABLE IF NOT EXISTS public.financials
(
    company_id character varying(10) COLLATE pg_catalog."default",
    year integer,
    revenue numeric,
    net_income numeric,
    roa numeric,
    roe numeric
);

CREATE TABLE IF NOT EXISTS public.governance
(
    company_id character varying(10) COLLATE pg_catalog."default",
    year integer,
    board_independence numeric,
    female_board numeric,
    exec_comp_to_revenue numeric
);

CREATE TABLE IF NOT EXISTS public.risk
(
    company_id character varying(10) COLLATE pg_catalog."default",
    year integer,
    controversey_score numeric,
    regulatory_fines numeric,
    esg_risk_rating character varying(50) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.social
(
    company_id character varying(10) COLLATE pg_catalog."default",
    year integer,
    employee_turnover numeric,
    diversity numeric,
    training_hours numeric
);

CREATE TABLE IF NOT EXISTS public.stock_performance
(
    company_id character varying(10) COLLATE pg_catalog."default",
    year integer,
    stock_price_start numeric,
    stock_price_end numeric,
    annual_return numeric,
    market_cap numeric
);
END;